server:
  port: 9000
  servlet:
    context-path: /chat-service
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      database: chat-service